customhost = "database-1.c8fkypxc9olt.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "ongyeeyung-employee"
customregion = "us-east-1"
